### PR TITLE
Add DGM header and footer

### PR DESCRIPTION
**Pull request by markbrough**
- Require bower and install DGM header and footer, plus dependencies
- Include DGM header and footer
- Slight adjustment to procurement-analytics stylesheet to compensate new position of navbar.
- Tell Travis to install bower components

### CODE REVIEW

**Comment by markbrough** [comment]
NB see also https://github.com/mxabierto/dgm-navbar/pull/11 to fix URLs so that they point to e.g. `https://datos.gob.mx/herramientas` rather than `https://contraciones.datos.gob.mx/herramientas`

**Comment by defvol** [comment]
hey @chuckcfs could you check this out?

**Comment by chuckcfs** [comment]
@rodowi sure thing

**Comment by chuckcfs** [comment]
done

screen shot 2015-10-23 at 12 48 32

**Comment by markbrough** [comment]
Thanks @chuckcfs! Would also push this to master if you're happy.

**Comment by defvol** [comment]
I'm pushing to master...

**Pull request merged**
